import 'dart:convert';

import 'package:agentkit_platform/agentkit_platform.dart';
import 'package:test/test.dart';

void main() {
  group('WebManifestEmitter', () {
    test('patches shortcuts and protocol_handlers from agent manifest', () {
      const baseManifest = '''
{
    "name": "demo",
    "short_name": "demo",
    "start_url": "."
}
''';
      final agentManifest = AgentManifest.fromJson(<String, Object?>{
        'version': 1,
        'platform': 'web',
        'tools': [
          <String, Object?>{
            'qualifiedName': 'app_cart_total',
            'namespace': 'app',
            'name': 'cart_total',
            'description': 'Return cart total',
            'kind': 'tool',
            'inputSchema': <String, Object?>{'type': 'object'},
          },
        ],
      });

      final output = const WebManifestEmitter().emit(
        existingManifestJson: baseManifest,
        manifest: agentManifest,
      );
      final map = jsonDecode(output) as Map<String, Object?>;
      final shortcuts = map['shortcuts'] as List;
      expect(shortcuts, hasLength(1));
      expect(shortcuts.first['url'], '/agent/invoke?name=app_cart_total');

      final handlers = map['protocol_handlers'] as List;
      expect(handlers, isNotEmpty);
      expect(handlers.first['protocol'], 'web+agentkit');
      expect(map['name'], 'demo');
    });

    test('matches golden manifest output', () {
      final output = const WebManifestEmitter().emit(
        existingManifestJson: _fixtureBaseWebManifest,
        manifest: _fixtureAgentManifest,
      );
      expect(output.trim(), _goldenWebManifest.trim());
    });
  });

  group('WebMcpJsEmitter', () {
    test('emits feature-detect registerTool loop', () {
      final js = const WebMcpJsEmitter().emit(_fixtureAgentManifest);
      expect(js, contains("'modelContext' in nav"));
      expect(js, contains('registerTool'));
      expect(js, contains('app_cart_total'));
      expect(js, contains('encodeURIComponent(tool.name)'));
      expect(js, contains('application/json'));
    });

    test('matches golden js output', () {
      final js = const WebMcpJsEmitter().emit(_fixtureAgentManifest);
      expect(js, _goldenWebMcpJs);
    });

    test('skips non-tool intents', () {
      final manifest = AgentManifest.fromJson(<String, Object?>{
        'version': 1,
        'platform': 'web',
        'tools': [
          <String, Object?>{
            'qualifiedName': 'app_errors',
            'namespace': 'app',
            'name': 'errors',
            'description': 'errors resource',
            'kind': 'resource',
            'inputSchema': <String, Object?>{'type': 'object'},
          },
        ],
      });
      final js = const WebMcpJsEmitter().emit(manifest);
      expect(js, isNot(contains('app_errors')));
      expect(js, contains('var tools = ['));
      expect(js, contains('];'));
      expect(js.split('var tools = [').last.split('];').first.trim(), isEmpty);
    });
  });

  group('AgentManifest', () {
    test('reads shortcuts and intents arrays', () {
      final manifest = AgentManifest.fromJson(<String, Object?>{
        'version': 1,
        'platform': 'android',
        'shortcuts': [
          <String, Object?>{
            'qualifiedName': 'app_ping',
            'namespace': 'app',
            'name': 'ping',
            'description': 'ping',
            'kind': 'tool',
            'inputSchema': <String, Object?>{'type': 'object'},
          },
        ],
      });
      expect(manifest.entries, hasLength(1));
      expect(manifest.tools.first.qualifiedName, 'app_ping');
    });
  });
}

const _fixtureBaseWebManifest = '''
{
    "name": "test_app",
    "short_name": "test_app",
    "start_url": ".",
    "display": "standalone"
}
''';

final _fixtureAgentManifest = AgentManifest.fromJson(<String, Object?>{
  'version': 1,
  'platform': 'web',
  'tools': [
    <String, Object?>{
      'qualifiedName': 'app_cart_total',
      'namespace': 'app',
      'name': 'cart_total',
      'description': 'Return cart total',
      'kind': 'tool',
      'inputSchema': <String, Object?>{'type': 'object'},
    },
  ],
});

const _goldenWebManifest = '''
{
    "name": "test_app",
    "short_name": "test_app",
    "start_url": ".",
    "display": "standalone",
    "shortcuts": [
        {
            "name": "Cart Total",
            "short_name": "Cart Total",
            "description": "Return cart total",
            "url": "/agent/invoke?name=app_cart_total"
        }
    ],
    "protocol_handlers": [
        {
            "protocol": "web+agentkit",
            "url": "/agent/invoke?protocol=%s"
        },
        {
            "protocol": "web+agentkit",
            "url": "/agent/invoke?name=app_cart_total&payload=%s"
        }
    ]
}''';

const _goldenWebMcpJs = '''
// Generated by agentkit_platform — do not edit by hand.
(function agentkitWebMcpBootstrap(global) {
  'use strict';
  var nav = global.navigator;
  if (!nav || !('modelContext' in nav) || typeof nav.modelContext.registerTool !== 'function') {
    return;
  }
  var invokePath = "/agent/invoke";
  var tools = [
  {
    "name": "app_cart_total",
    "description": "Return cart total",
    "inputSchema": {
      "type": "object"
    }
  }
];
  for (var i = 0; i < tools.length; i += 1) {
    var tool = tools[i];
    nav.modelContext.registerTool({
      name: tool.name,
      description: tool.description,
      inputSchema: tool.inputSchema,
      execute: function (args) {
        return global.fetch(invokePath + '?name=' + encodeURIComponent(tool.name), {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(args || {}),
        }).then(function (response) {
          return response.json();
        });
      },
    });
  }
})(typeof globalThis !== 'undefined' ? globalThis : window);
''';
