import 'dart:convert';

import '../agent_manifest.dart';

/// Generates `web/agentkit_webmcp.generated.js` for static WebMCP bootstrap.
final class WebMcpJsEmitter {
  const WebMcpJsEmitter({this.invokePath = '/agent/invoke'});

  final String invokePath;

  String emit(final AgentManifest manifest) {
    final tools = manifest.tools
        .map(
          (final tool) => <String, Object?>{
            'name': tool.qualifiedName,
            'description': tool.description,
            'inputSchema': tool.inputSchema,
          },
        )
        .toList(growable: false);

    final toolsJson = const JsonEncoder.withIndent('  ').convert(tools);
    final invokePathJson = jsonEncode(invokePath);
    return '''
// Generated by agentkit_platform — do not edit by hand.
(function agentkitWebMcpBootstrap(global) {
  'use strict';
  var nav = global.navigator;
  if (!nav || !('modelContext' in nav) || typeof nav.modelContext.registerTool !== 'function') {
    return;
  }
  var invokePath = $invokePathJson;
  var tools = $toolsJson;
  for (var i = 0; i < tools.length; i += 1) {
    var tool = tools[i];
    try {
      nav.modelContext.registerTool({
        name: tool.name,
        description: tool.description,
        inputSchema: tool.inputSchema,
        execute: function (args) {
          return global.fetch(invokePath + '?name=' + encodeURIComponent(tool.name), {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(args || {}),
          }).then(function (response) {
            return response.json();
          });
        },
      });
    } catch (e) {
      // Hot restart / Dart bootstrap may have registered the same name.
    }
  }
})(typeof globalThis !== 'undefined' ? globalThis : window);
''';
  }
}
