name: dart_forwarding_client
description: A Dart client for connecting to the forwarding server
version: 0.1.0
homepage: https://github.com/your-username/flutter-inspector

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  web_socket_channel: ^2.4.0
  uuid: ^4.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  jaspr: ^0.10.0
  jaspr_builder: ^0.10.0
  jaspr_bootstrap: ^0.3.0
  build_runner: ^2.4.8
