name: dart_proxy
description: A Flutter-based proxy server for widget inspection.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  vm_service: ^13.0.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
