name: dart_proxy
description: A Flutter-based proxy server for widget inspection.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0
  flutter: ">=3.19.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  vm_service: ^13.0.0
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  json_annotation: ^4.8.1
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
