name: mcp_mcp_dart_forwarding_client
description: A Dart client for connecting to the forwarding server
version: 0.1.0
homepage: https://github.com/Arenukvern/mcp_flutter

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  web_socket_channel: ^3.0.2
  uuid: ^4.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  build_runner: ^2.4.8
