import '../agent_manifest.dart';
import 'emitter_utils.dart';

/// Emits `res/xml/agentkit_shortcuts.xml` for Android dynamic shortcuts.
///
/// Same XML applies to stock Android, Xiaomi HyperOS, and Huawei APK builds;
/// OEM-specific behavior is documented separately.
final class AndroidShortcutsXmlEmitter {
  const AndroidShortcutsXmlEmitter({
    this.protocolScheme = 'agentkit',
  });

  final String protocolScheme;

  String emit(final AgentManifest manifest) {
    final buffer = StringBuffer()
      ..writeln('<?xml version="1.0" encoding="utf-8"?>')
      ..writeln(
        '<!-- Generated by agentkit_platform — do not edit by hand. -->',
      )
      ..writeln(
        '<shortcuts xmlns:android="http://schemas.android.com/apk/res/android">',
      );

    for (final tool in manifest.tools) {
      final shortLabel = escapeXml(humanizeAgentName(tool.name));
      final longLabel = escapeXml(
        tool.description.isEmpty ? shortLabel : tool.description,
      );
      final data = escapeXml('$protocolScheme://invoke/${tool.qualifiedName}');
      buffer
        ..writeln('  <shortcut')
        ..writeln('      android:shortcutId="${escapeXml(tool.qualifiedName)}"')
        ..writeln('      android:enabled="true"')
        ..writeln('      android:shortcutShortLabel="$shortLabel"')
        ..writeln('      android:shortcutLongLabel="$longLabel">')
        ..writeln('    <intent')
        ..writeln('        android:action="android.intent.action.VIEW"')
        ..writeln('        android:data="$data" />')
        ..writeln('  </shortcut>');
    }

    buffer.writeln('</shortcuts>');
    return buffer.toString();
  }
}

/// Manifest snippet to add under `<application>` once (via `init agentkit-platform`).
const kAndroidShortcutsManifestSnippet = '''
<!-- agentkit-platform: begin -->
<meta-data
    android:name="android.app.shortcuts"
    android:resource="@xml/agentkit_shortcuts" />
<!-- agentkit-platform: end -->
''';
