import '../agent_manifest.dart';
import 'emitter_utils.dart';

/// Emits Swift App Intents + shortcuts provider for iOS and macOS.
///
/// Logic mirrors [generateAppleAgentManifest] in `agentkit_apple`; this emitter
/// turns manifest rows into compile-time Swift for `Runner/Generated/`.
final class AppleSwiftAppIntentsEmitter {
  const AppleSwiftAppIntentsEmitter({
    this.protocolScheme = 'agentkit',
  });

  final String protocolScheme;

  String emit(final AgentManifest manifest) {
    final buffer = StringBuffer()
      ..writeln('// Generated by agentkit_platform — do not edit by hand.')
      ..writeln('import AppIntents')
      ..writeln('import Foundation')
      ..writeln('#if canImport(UIKit)')
      ..writeln('import UIKit')
      ..writeln('#elseif canImport(AppKit)')
      ..writeln('import AppKit')
      ..writeln('#endif')
      ..writeln();

    final shortcutLines = <String>[];
    for (final tool in manifest.tools) {
      final typeName = swiftIntentTypeName(tool.qualifiedName);
      final title = escapeSwiftString(
        tool.description.isEmpty
            ? humanizeAgentName(tool.name)
            : tool.description,
      );
      final phrase = escapeSwiftString(humanizeAgentName(tool.name));
      buffer
        ..writeln('@available(iOS 16.0, macOS 13.0, *)')
        ..writeln('struct $typeName: AppIntent {')
        ..writeln('  static var title: LocalizedStringResource = "$title"')
        ..writeln()
        ..writeln('  func perform() async throws -> some IntentResult {')
        ..writeln(
          '    await AgentKitNativeBridge.invoke(qualifiedName: "${escapeSwiftString(tool.qualifiedName)}")',
        )
        ..writeln('    return .result()')
        ..writeln('  }')
        ..writeln('}')
        ..writeln();
      shortcutLines.add(
        '    AppShortcut(intent: $typeName(), phrases: ["$phrase"])',
      );
    }

    buffer
      ..writeln('@available(iOS 16.0, macOS 13.0, *)')
      ..writeln('struct AgentKitShortcutsProvider: AppShortcutsProvider {')
      ..writeln('  static var appShortcuts: [AppShortcut] {')
      ..writeln('    [');
    if (shortcutLines.isEmpty) {
      buffer.writeln('    ]');
    } else {
      buffer.writeln('${shortcutLines.join(',\n')},');
      buffer.writeln('    ]');
    }
    buffer
      ..writeln('  }')
      ..writeln('}')
      ..writeln()
      ..writeln('enum AgentKitNativeBridge {')
      ..writeln('  static func invoke(qualifiedName: String) async {')
      ..writeln(
        '    guard let url = URL(string: "$protocolScheme://invoke/\\(qualifiedName)") else { return }',
      )
      ..writeln('    #if canImport(UIKit)')
      ..writeln('    await UIApplication.shared.open(url)')
      ..writeln('    #elseif canImport(AppKit)')
      ..writeln('    NSWorkspace.shared.open(url)')
      ..writeln('    #endif')
      ..writeln('  }')
      ..writeln('}');

    return buffer.toString();
  }
}
