import '../agent_manifest.dart';

/// Emits a `.desktop` file registering `x-scheme-handler/agentkit`.
final class LinuxDesktopEntryEmitter {
  const LinuxDesktopEntryEmitter({
    this.protocolScheme = 'agentkit',
    this.appName = 'Flutter App',
    this.execPlaceholder = '@EXEC@',
  });

  final String protocolScheme;
  final String appName;
  final String execPlaceholder;

  String emit(final AgentManifest manifest) {
    final toolsComment = manifest.tools
        .map((final t) => '# tool: ${t.qualifiedName}')
        .join('\n');
    return '''
# Generated by agentkit_platform — do not edit by hand.
$toolsComment
[Desktop Entry]
Type=Application
Name=$appName (AgentKit)
Comment=AgentKit deep-link handler
Exec=$execPlaceholder %u
MimeType=x-scheme-handler/$protocolScheme;
NoDisplay=true
Terminal=false
''';
  }
}

/// Shell snippet to register the desktop entry with `xdg-mime` (run once).
const kLinuxXdgRegisterSnippet = '''
# agentkit-platform: begin
# xdg-mime default agentkit_protocol.desktop x-scheme-handler/agentkit
# agentkit-platform: end
''';
