name: script_utils
description: A collection of utility scripts.
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.0 # Using a recent stable version

dev_dependencies:
  lints: ^2.0.0 # Optional, but good practice
  test: ^1.24.0 # Optional
