#!/usr/bin/env bash
# Run the flutter_test_app showcase on macOS and print the canonical VM
# websocket URI once the app is reachable. The app is left running in the
# foreground so `flutter r` / `R` / `q` still work interactively.
#
# Typical agent use:
#   make showcase-stop          # end stray instances first
#   make showcase               # in one terminal
#   bash .showcase/intentcall_examples.sh
#
# That second script discovers the published link, calls
# app_intentcall_bridge_ping, and prints the MCP serve command.
# Debug inspector calls still use the VM URI printed below.
#
# The showcase includes a Capture section with a native platform view:
#   macOS — AppKitView + Swift factory (this script)
#   web   — flutter run -d chrome --web-port=8080 (HtmlElementView; CDP capture)
# For macOS desktop_window / validate-runtime, grant Screen Recording to the
# terminal or IDE running flutter-mcp-toolkit. Web uses CDP tab capture (ADR 0007).

set -u
set -o pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${here}/.." && pwd)"
app_dir="${repo_root}/flutter_test_app"
showcase_dir="${repo_root}/.showcase"
pid_file="${showcase_dir}/flutter.pid"
app_log="${showcase_dir}/flutter_app.log"

stop_running_showcase() {
  bash "${here}/stop_showcase.sh"
}

trap 'stop_running_showcase; printf "\n[showcase] log retained at %s\n" "${app_log}"' EXIT INT TERM

mkdir -p "${showcase_dir}"
stop_running_showcase

printf "[showcase] running flutter test app on macOS…\n"
printf "[showcase] logs → %s\n\n" "${app_log}"

cd "${app_dir}"

# Log to file; stream to terminal for interactive use.
flutter run -d macos --debug 2>&1 | tee "${app_log}" &
flutter_pid=$!
echo "${flutter_pid}" > "${pid_file}"

printf "[showcase] flutter pid %s (also in %s)\n" "${flutter_pid}" "${pid_file}"

# Wait up to 180s for the VM service endpoint to appear in the log.
vm_uri=""
for _ in $(seq 1 180); do
  vm_uri="$(grep -Eo 'http://127\.0\.0\.1:[0-9]+/[A-Za-z0-9_=-]+/' "${app_log}" | tail -1)"
  if [ -n "${vm_uri}" ]; then break; fi
  sleep 1
done

if [ -z "${vm_uri}" ]; then
  printf "\n[showcase] gave up waiting for Dart VM Service URI (180s).\n" >&2
  wait "${flutter_pid}" 2>/dev/null || true
  exit 1
fi

# Convert http://host:port/token/ → ws://host:port/token/ws
ws_uri="${vm_uri/http:/ws:}ws"

printf "\n"
printf "[showcase] Dart VM Service:  %s\n" "${vm_uri}"
printf "[showcase] canonical WS URI: %s\n" "${ws_uri}"

intentcall_root="${INTENTCALL_ROOT:-}"
if [[ -z "${intentcall_root}" && -d "${repo_root}/../intentcall/packages/intentcall_cli" ]]; then
  intentcall_root="${repo_root}/../intentcall"
elif [[ -z "${intentcall_root}" && -d "${repo_root}/../agentkit/packages/intentcall_cli" ]]; then
  intentcall_root="${repo_root}/../agentkit"
fi

scheme="mcpfluttertest"
link_file="${HOME}/.intentcall/links/${scheme}.json"
link_ready=""
for _ in $(seq 1 30); do
  if [[ -f "${link_file}" ]]; then
    link_ready=1
    break
  fi
  sleep 1
done

examples="${showcase_dir}/intentcall_examples.sh"
{
  printf '#!/usr/bin/env bash\n'
  printf '# Generated by scripts/run_showcase.sh. Requires the macOS showcase to be running.\n'
  printf 'set -euo pipefail\n'
  printf 'intentcall() {\n'
  if [[ -n "${intentcall_root}" ]]; then
    printf '  (cd %q && dart run bin/intentcall.dart "$@")\n' "${intentcall_root}/packages/intentcall_cli"
  else
    printf '  command intentcall "$@"\n'
  fi
  printf '}\n'
  printf 'scheme=%q\n' "${scheme}"
  printf 'ws_uri=%q\n' "${ws_uri}"
  printf 'mode="${1:-demo}"\n'
  printf 'case "${mode}" in\n'
  printf '  demo)\n'
  printf '    echo "== discover ${scheme} =="\n'
  printf '    intentcall link discover --scheme "${scheme}"\n'
  printf '    echo "== call app_intentcall_bridge_ping =="\n'
  printf '    intentcall link call --scheme "${scheme}" --name app_intentcall_bridge_ping --args '\''{"echo":"hello"}'\''\n'
  printf '    echo\n'
  printf '    echo "Production-shaped MCP door (blocks, no widget inspector):"\n'
  printf '    echo "  bash %q serve-link"\n' "${examples}"
  printf '    echo "Debug MCP door (prefers this VM, blocks):"\n'
  printf '    echo "  bash %q serve-debug"\n' "${examples}"
  printf '    ;;\n'
  printf '  serve-link)\n'
  printf '    exec intentcall mcp serve --scheme "${scheme}"\n'
  printf '    ;;\n'
  printf '  serve-debug)\n'
  printf '    exec intentcall mcp serve --auto --vm-service-uri "${ws_uri}" --scheme "${scheme}"\n'
  printf '    ;;\n'
  printf '  *)\n'
  printf '    echo "Usage: bash %q [demo|serve-link|serve-debug]" >&2\n' "${examples}"
  printf '    exit 64\n'
  printf '    ;;\n'
  printf 'esac\n'
} >"${examples}"
chmod +x "${examples}"

printf "\n"
if [[ -n "${link_ready}" ]]; then
  printf "[showcase] link record: %s\n" "${link_file}"
else
  printf "[showcase] link record not visible yet at %s\n" "${link_file}"
  printf "[showcase] the app publishes it after the first frame when publishSurfaceLink is on.\n"
fi
if [[ -z "${intentcall_root}" ]]; then
  printf "[showcase] intentcall CLI not found next to this repo. Set INTENTCALL_ROOT or put intentcall on PATH.\n"
else
  printf "[showcase] intentcall CLI: %s\n" "${intentcall_root}/packages/intentcall_cli"
fi
printf "[showcase] reproducible session, second terminal:\n"
printf "  bash %s\n" "${examples}"
printf "\n"
printf "  export WS='%s'\n" "${ws_uri}"
printf "  flutter-mcp-toolkit exec --name semantic_snapshot \\\\\n"
printf "    --args \"{\\\"connection\\\":{\\\"targetId\\\":\\\"\$WS\\\"}}\"\n"
printf "\n"
printf "[showcase] app is running. Press r for hot reload, q to quit.\n"
printf "[showcase] to stop from another terminal: make showcase-stop\n\n"

wait "${flutter_pid}"
