import 'package:agentkit_platform/agentkit_platform.dart';
import 'package:test/test.dart';

void main() {
  final manifest = AgentManifest.fromJson(<String, Object?>{
    'version': 1,
    'platform': 'android',
    'shortcuts': [
      <String, Object?>{
        'qualifiedName': 'app_cart_total',
        'namespace': 'app',
        'name': 'cart_total',
        'description': 'Return cart total',
        'kind': 'tool',
        'inputSchema': <String, Object?>{'type': 'object'},
      },
    ],
  });

  group('AndroidShortcutsXmlEmitter', () {
    test('emits shortcut with agentkit deep link', () {
      final xml = const AndroidShortcutsXmlEmitter().emit(manifest);
      expect(xml, contains('android:shortcutId="app_cart_total"'));
      expect(xml, contains('agentkit://invoke/app_cart_total'));
      expect(xml, contains('Cart Total'));
    });

    test('matches golden xml', () {
      final xml = const AndroidShortcutsXmlEmitter().emit(manifest);
      expect(xml.trim(), _goldenAndroidShortcutsXml.trim());
    });
  });

  group('AppleSwiftAppIntentsEmitter', () {
    test('emits AppIntent and AppShortcutsProvider', () {
      final swift = const AppleSwiftAppIntentsEmitter().emit(manifest);
      expect(swift, contains('struct AppCartTotalIntent: AppIntent'));
      expect(swift, contains('AgentKitShortcutsProvider'));
      expect(swift, contains('AgentKitNativeBridge'));
      expect(swift, contains('agentkit://invoke/'));
    });

    test('matches golden swift', () {
      final swift = const AppleSwiftAppIntentsEmitter().emit(manifest);
      expect(swift.trim(), _goldenAppleSwift.trim());
    });
  });

  group('LinuxDesktopEntryEmitter', () {
    test('registers x-scheme-handler', () {
      final desktop = const LinuxDesktopEntryEmitter().emit(manifest);
      expect(desktop, contains('x-scheme-handler/agentkit'));
      expect(desktop, contains('tool: app_cart_total'));
    });

    test('matches golden desktop entry', () {
      final desktop = const LinuxDesktopEntryEmitter().emit(manifest);
      expect(desktop.trim(), _goldenLinuxDesktop.trim());
    });
  });

  group('WindowsProtocolEmitter', () {
    test('emits registry script', () {
      final reg = const WindowsProtocolEmitter().emit(manifest);
      expect(reg, contains(r'[HKEY_CURRENT_USER\Software\Classes\agentkit]'));
      expect(reg, contains('; tool: app_cart_total'));
    });

    test('emits msix fragment', () {
      final msix = const WindowsProtocolEmitter().emitMsixFragment(manifest);
      expect(msix, contains('windows.protocol'));
      expect(msix, contains('Name="agentkit"'));
    });
  });
}

const _goldenAndroidShortcutsXml = '''
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by agentkit_platform — do not edit by hand. -->
<shortcuts xmlns:android="http://schemas.android.com/apk/res/android">
  <shortcut
      android:shortcutId="app_cart_total"
      android:enabled="true"
      android:shortcutShortLabel="Cart Total"
      android:shortcutLongLabel="Return cart total">
    <intent
        android:action="android.intent.action.VIEW"
        android:data="agentkit://invoke/app_cart_total" />
  </shortcut>
</shortcuts>''';

const _goldenAppleSwift = r'''
// Generated by agentkit_platform — do not edit by hand.
import AppIntents
import Foundation
#if canImport(UIKit)
import UIKit
#elseif canImport(AppKit)
import AppKit
#endif

@available(iOS 16.0, macOS 13.0, *)
struct AppCartTotalIntent: AppIntent {
  static var title: LocalizedStringResource = "Return cart total"

  func perform() async throws -> some IntentResult {
    await AgentKitNativeBridge.invoke(qualifiedName: "app_cart_total")
    return .result()
  }
}

@available(iOS 16.0, macOS 13.0, *)
struct AgentKitShortcutsProvider: AppShortcutsProvider {
  static var appShortcuts: [AppShortcut] {
    [
    AppShortcut(intent: AppCartTotalIntent(), phrases: ["Cart Total"]),
    ]
  }
}

enum AgentKitNativeBridge {
  static func invoke(qualifiedName: String) async {
    guard let url = URL(string: "agentkit://invoke/\(qualifiedName)") else { return }
    #if canImport(UIKit)
    await UIApplication.shared.open(url)
    #elseif canImport(AppKit)
    NSWorkspace.shared.open(url)
    #endif
  }
}''';

const _goldenLinuxDesktop = '''
# Generated by agentkit_platform — do not edit by hand.
# tool: app_cart_total
[Desktop Entry]
Type=Application
Name=Flutter App (AgentKit)
Comment=AgentKit deep-link handler
Exec=@EXEC@ %u
MimeType=x-scheme-handler/agentkit;
NoDisplay=true
Terminal=false''';
